import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.clear())
  await page.goto('/editor-v2')
})

test('하단 자소는 캐러셀 기준을 바꾸고 중앙 글자는 상세 편집을 연다', async ({ page }) => {
  const composition = page.getByRole('region', { name: '곰 구성' })
  await expect(composition.getByRole('button')).toHaveCount(4)
  await expect(composition.getByText('ㄱ', { exact: true })).toBeVisible()
  await expect(composition.getByText('ㅗ', { exact: true })).toBeVisible()
  await expect(composition.getByText('ㅁ', { exact: true })).toBeVisible()
  await expect(composition.getByText('가로중성 + 받침', { exact: true })).toBeVisible()

  await composition.getByRole('button', { name: '중성 ㅗ 캐러셀 기준으로 선택' }).click()
  await expect(page.getByRole('region', { name: '중성 문맥 캐러셀' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '곰 편집' })).toBeVisible()
  await page.getByRole('button', { name: /^ㅗ .* 획 선택$/ }).first().focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: '중성 ㅗ 편집' })).toBeVisible()
})

test('레이아웃 편집은 독립된 전체 적용 흐름을 유지한다', async ({ page }) => {
  await page.getByRole('button', { name: '현재 글자의 레이아웃 편집 열기' }).click()
  await expect(page.getByRole('heading', { name: '곰 레이아웃' })).toBeVisible()
  await expect(page.getByText('같은 구조의 모든 글자에 적용')).toBeVisible()
  await expect(page.getByRole('region', { name: '곰 레이아웃 영역' })).toBeVisible()
  await expect(page.getByRole('button', { name: '가로 기준선 1 이동' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'ㄱ 레이아웃 박스 활성' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'ㅗ 레이아웃 박스 활성' })).toBeVisible()
  const finalBox = page.getByRole('button', { name: 'ㅁ 레이아웃 박스 활성' })
  await expect(finalBox).toBeVisible()
  await finalBox.click()
  await expect(page.getByRole('button', { name: 'ㅁ 위쪽 여백 조절' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'ㅁ 아래쪽 여백 조절' })).toBeVisible()
  await page.getByRole('button', { name: '뒤로' }).click()
  await expect(page.getByRole('heading', { name: '곰 편집' })).toBeVisible()
})

test('혼합중성의 가로부와 세로부를 각각 레이아웃 박스로 선택한다', async ({ page }) => {
  await page.getByRole('button', { name: '중성 ㅗ 캐러셀 기준으로 선택' }).click()
  for (let index = 0; index < 19; index += 1) await page.getByRole('button', { name: /^다음 중성 글자/ }).click()
  await page.getByRole('button', { name: '현재 글자의 레이아웃 편집 열기' }).click()
  await expect(page.getByRole('button', { name: /가로부 레이아웃 박스 활성/ })).toBeVisible()
  const verticalPart = page.getByRole('button', { name: /세로부 레이아웃 박스 활성/ })
  await expect(verticalPart).toBeVisible()
  await verticalPart.click()
  await expect(page.getByRole('button', { name: /세로부 위쪽 여백 조절/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /세로부 오른쪽 여백 조절/ })).toBeVisible()
  const bottomEdge = page.getByRole('button', { name: /세로부 아래쪽 여백 조절/ })
  const before = await bottomEdge.boundingBox()
  if (!before) throw new Error('혼합중성 세로부 아래쪽 경계를 찾지 못했습니다.')
  await page.mouse.move(before.x + before.width / 2, before.y + before.height / 2)
  await page.mouse.down()
  await page.mouse.move(before.x + before.width / 2, before.y + before.height / 2 + 20, { steps: 4 })
  await page.mouse.up()
  const after = await bottomEdge.boundingBox()
  expect(after?.y ?? 0).toBeGreaterThan(before.y)
})

test('스와이퍼의 자소 전체 편집은 현재 글자 보정으로 저장한다', async ({ page }) => {
  await expect(page.getByRole('region', { name: '곰 글자 보정 속성' })).toHaveCount(0)
  await page.getByRole('button', { name: '곰의 ㄱ 편집' }).click()
  const trackpad = page.getByRole('group', { name: '현재 글자의 자소 위치와 비율을 보정하는 트랙패드' })
  await trackpad.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByText('현재 글자 보정', { exact: true })).toBeVisible()
  await expect(page.getByText('곰에서만 적용')).toBeVisible()
  await expect(page.getByText(/x 0\.005/)).toBeVisible()
  await page.getByRole('button', { name: '편집 히스토리' }).click()
  await expect(page.getByText(/곰의 ㄱ 위치 보정/)).toBeVisible()
  await expect(page.getByText(/범위 현재 글자 곰/)).toBeVisible()
})

test('현재 글자 보정을 한 번에 초기화한다', async ({ page }) => {
  await page.getByRole('button', { name: '곰의 ㄱ 편집' }).click()
  const trackpad = page.getByRole('group', { name: '현재 글자의 자소 위치와 비율을 보정하는 트랙패드' })
  await trackpad.focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('button', { name: '위치 초기화' })).toBeVisible()
  await page.getByRole('button', { name: '모두 초기화' }).click()
  await expect(page.getByRole('region', { name: '곰 글자 보정 속성' })).toHaveCount(0)
})

test('자소 기본형은 단독 화면과 레이아웃별 보기 카드에서 편집한다', async ({ page }) => {
  await page.getByRole('button', { name: 'ㄱ ㄱ-1 획 선택' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: '초성 ㄱ 편집' })).toBeVisible()
  await expect(page.getByText('초성 기본형', { exact: true })).toHaveCount(0)
  await expect(page.getByText('초성 레이아웃 전체에 일괄 적용', { exact: true })).toHaveCount(0)
  await expect(page.getByText('레이아웃별 적용', { exact: true })).toHaveCount(0)
  await expect(page.getByText('보기 전용', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'ㄱ 단독 미리보기' })).toBeVisible()
  const contexts = page.getByRole('region', { name: 'ㄱ 레이아웃별 적용 미리보기' })
  await expect(contexts).toBeVisible()
  const contextBox = await contexts.boundingBox()
  const canvasBox = await page.getByRole('region', { name: 'ㄱ 단독 미리보기' }).boundingBox()
  expect(contextBox?.y ?? Infinity).toBeLessThan(canvasBox?.y ?? 0)
  await expect(page.getByTitle('초성만')).toBeVisible()
  await expect(page.getByTitle('초+세로중', { exact: true })).toBeVisible()
})

test('가로·세로 모음 기본형은 각각의 모음 박스 비율로 표시한다', async ({ page }) => {
  await page.getByRole('button', { name: '중성 ㅗ 캐러셀 기준으로 선택' }).click()
  await page.getByRole('button', { name: /^ㅗ .* 획 선택$/ }).first().focus()
  await page.keyboard.press('Enter')
  const horizontalPreview = page.getByRole('region', { name: 'ㅗ 단독 미리보기' })
  const horizontalBox = await horizontalPreview.boundingBox()
  if (!horizontalBox) throw new Error('가로 모음 기본형 미리보기를 찾지 못했습니다.')
  expect(horizontalBox.width).toBeGreaterThan(horizontalBox.height * 1.5)

  await page.getByRole('button', { name: '뒤로' }).click()
  for (let index = 0; index < 21 && await page.getByRole('button', { name: '중성 ㅏ 캐러셀 기준으로 선택' }).count() === 0; index += 1) {
    await page.getByRole('button', { name: /^이전 중성 글자/ }).click()
  }
  await page.getByRole('button', { name: /^ㅏ .* 획 선택$/ }).first().focus()
  await page.keyboard.press('Enter')
  const verticalPreview = page.getByRole('region', { name: 'ㅏ 단독 미리보기' })
  const verticalBox = await verticalPreview.boundingBox()
  if (!verticalBox) throw new Error('세로 모음 기본형 미리보기를 찾지 못했습니다.')
  expect(verticalBox.height).toBeGreaterThan(verticalBox.width * 1.5)
})

test('기본형 화면에서만 개별 획과 꼭지점으로 들어간다', async ({ page }) => {
  await page.getByRole('button', { name: 'ㄱ ㄱ-1 획 선택' }).focus()
  await page.keyboard.press('Enter')
  const stroke = page.getByRole('button', { name: 'ㄱ ㄱ-1 획 선택' })
  await stroke.focus()
  await page.keyboard.press('Enter')
  const startPoint = page.locator('[aria-label="ㄱ ㄱ-1 시작 꼭짓점 선택"]')
  await expect(startPoint).toBeVisible()
  await startPoint.click()
  await expect(page.getByRole('group', { name: '한 손가락으로 이동하고 두 손가락으로 획 비율을 조절하는 트랙패드' })).toBeVisible()
  await expect(page.getByRole('complementary', { name: '획 편집 도구' })).toBeVisible()
  await page.getByRole('button', { name: '곡선화' }).click()
  await expect(page.getByRole('button', { name: '직선화' })).toBeVisible()
  const curveHandle = page.getByRole('button', { name: /시작 꼭짓점 나가는 곡선 손잡이 선택/ })
  await expect(curveHandle).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('navigation', { name: '현재 선택 단계' })).toContainText('나가는 곡선 손잡이')
  const handleXBefore = Number(await curveHandle.getAttribute('cx'))
  const curveTrackpad = page.getByRole('group', { name: '한 손가락으로 이동하고 두 손가락으로 획 비율을 조절하는 트랙패드' })
  await curveTrackpad.focus()
  await page.keyboard.press('ArrowRight')
  expect(Number(await curveHandle.getAttribute('cx'))).toBeGreaterThan(handleXBefore)
  await page.getByRole('button', { name: '직선화' }).click()
  await expect(curveHandle).toHaveCount(0)
  await page.getByRole('button', { name: '방향 잠금' }).click()
  await page.locator('[aria-label="ㄱ ㄱ-1 끝 꼭짓점 선택"]').click()
  const unlock = page.getByRole('button', { name: '방향 잠금 해제' })
  await expect(unlock).toHaveAttribute('aria-pressed', 'true')
  await unlock.click()
  await expect(page.getByRole('button', { name: '방향 잠금' })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: '선 추가' }).click()
  const addedStroke = page.getByRole('button', { name: /^ㄱ stroke-\d+ 획 선택$/ })
  await expect(addedStroke).toHaveCount(1)
  await expect(addedStroke).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '획 삭제' }).click()
  await expect(addedStroke).toHaveCount(0)
  await page.getByRole('button', { name: '뒤로' }).click()
  await expect(page.getByRole('heading', { name: '곰 편집' })).toBeVisible()
  await expect(page.getByText('글자 속 자소를 누르면 상세 편집으로 이동합니다')).toBeVisible()
  await expect(page.locator('[aria-label="ㄱ ㄱ-1 시작 꼭짓점 선택"]')).toHaveCount(0)
})

test('캐러셀에서 바꾼 글자도 선택한 자소 기준으로 트랙패드를 연다', async ({ page }) => {
  await page.getByRole('button', { name: '다음 초성 글자 놈' }).click()
  await expect(page.getByRole('heading', { name: '놈 편집' })).toBeVisible()
  await page.getByRole('button', { name: '중성 ㅗ 캐러셀 기준으로 선택' }).click()
  await page.getByRole('button', { name: '놈의 ㅗ 편집' }).click()
  await expect(page.getByRole('group', { name: '현재 글자의 자소 위치와 비율을 보정하는 트랙패드' })).toBeVisible()
  await expect(page.getByRole('button', { name: '중성 ㅗ 캐러셀 기준으로 선택' })).toBeVisible()
})
